### ISSUE TITLE
*NOT AN ISSUE* would love a video tutorial on this

### ISSUE THREAD

**Issue by bobbymannino** [total-typescript/untypeable#5]
Not an issue so feel free to close or delete but would love a video on this. I dont quite understand it from the docs, not because of the docs themselves but i struggle to understand documentation in general, videos always seem to get the point across. thank you.

**Comment by jellydn** [comment]
Just FYI - I've implemented a demo with this library. Hopefully you find this useful. 

https://github.com/jellydn/untypeable-wretch-demo

**Comment by mattpocock** [comment]
Here you go!

https://www.youtube.com/watch?v=bUts4HJJjV4

And Web Dev Simplified also made one:

https://www.youtube.com/watch?v=C_v0fcGEGbA
